Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Controllers/HumanResource/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Plugin.Widgets.HumanResource.Areas.Admin.Factories;
using Nop.Plugin.Widgets.HumanResource.Areas.Admin.Models.HumanResource;
using Nop.Plugin.Widgets.HumanResource.Services.HumanResource;
using Nop.Plugin.Widgets.HumanResource.Services.ExportImport;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Plugin.Widgets.HumanResource.Services.Security;
using Nop.Services.Helpers;
using System.Globalization;
using Nop.Services.Orders;
using Nop.Web.Framework.Controllers;
using System.IO;
using Nop.Plugin.Widgets.HumanResource.Core.Domains.HumanResource;
using Nop.Plugin.Widgets.HumanResource.Services.Common;

namespace Nop.Plugin.Widgets.HumanResource.Areas.Admin.Controllers.HumanResource
{
    public partial class EmployeeController : BaseAdminController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly IEmployeeModelFactory _employeeModelFactory;
        private readonly IEmployeeService _employeeService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly IPluginExportManager _exportManager;
        private readonly IPluginImportManager _importManager;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly IStaticCacheManager _staticCacheManager;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IStoreService _storeService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IPluginPdfService _pdfService;

        #endregion

        #region Ctor

        public EmployeeController(IAclService aclService,
            IEmployeeModelFactory employeeModelFactory,
            IEmployeeService employeeService,
            ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            IPluginExportManager exportManager,
            IPluginImportManager importManager,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPictureService pictureService,
            IStaticCacheManager staticCacheManager,
            IStoreMappingService storeMappingService,
            IStoreService storeService,
            IUrlRecordService urlRecordService,
            IWorkContext workContext,
            IDateTimeHelper dateTimeHelper,
            IPluginPdfService pdfService)
        {
            _aclService = aclService;
            _employeeModelFactory = employeeModelFactory;
            _employeeService = employeeService;
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _exportManager = exportManager;
            _importManager = importManager;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _pictureService = pictureService;
            _staticCacheManager = staticCacheManager;
            _storeMappingService = storeMappingService;
            _storeService = storeService;
            _urlRecordService = urlRecordService;
            _workContext = workContext;
            _dateTimeHelper = dateTimeHelper;
            _pdfService = pdfService;
        }

        #endregion

        #region Utilities

        protected virtual async Task UpdateLocalesAsync(Employee employee, EmployeeModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(employee,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(employee,
                    x => x.Description,
                    localized.Description,
                    localized.LanguageId);

                //search engine name
                var seName = await _urlRecordService.ValidateSeNameAsync(employee, localized.SeName, localized.Name, false);
                await _urlRecordService.SaveSlugAsync(employee, seName, localized.LanguageId);
            }
        }

        protected virtual async Task UpdatePictureSeoNamesAsync(Employee employee)
        {
            var picture = await _pictureService.GetPictureByIdAsync(employee.PictureId);
            if (picture != null)
                await _pictureService.SetSeoFilenameAsync(picture.Id, await _pictureService.GetPictureSeNameAsync(employee.Name));
        }

        protected virtual async Task SaveEmployeeAclAsync(Employee employee, EmployeeModel model)
        {
            employee.SubjectToAcl = model.SelectedCustomerRoleIds.Any();
            await _employeeService.UpdateEmployeeAsync(employee);

            var existingAclRecords = await _aclService.GetAclRecordsAsync(employee);
            var allCustomerRoles = await _customerService.GetAllCustomerRolesAsync(true);
            foreach (var customerRole in allCustomerRoles)
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                    //new role
                    if (!existingAclRecords.Any(acl => acl.CustomerRoleId == customerRole.Id))
                        await _aclService.InsertAclRecordAsync(employee, customerRole.Id);
                    else
                    {
                        //remove role
                        var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                        if (aclRecordToDelete != null)
                            await _aclService.DeleteAclRecordAsync(aclRecordToDelete);
                    }
        }

        protected virtual async Task SaveStoreMappingsAsync(Employee employee, EmployeeModel model)
        {
            employee.LimitedToStores = model.SelectedStoreIds.Any();
            await _employeeService.UpdateEmployeeAsync(employee);

            var existingStoreMappings = await _storeMappingService.GetStoreMappingsAsync(employee);
            var allStores = await _storeService.GetAllStoresAsync();
            foreach (var store in allStores)
                if (model.SelectedStoreIds.Contains(store.Id))
                    //new store
                    if (!existingStoreMappings.Any(sm => sm.StoreId == store.Id))
                        await _storeMappingService.InsertStoreMappingAsync(employee, store.Id);
                    else
                    {
                        //remove store
                        var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                        if (storeMappingToDelete != null)
                            await _storeMappingService.DeleteStoreMappingAsync(storeMappingToDelete);
                    }
        }

        #endregion

        #region List

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(APermissionProvider.ManageEmployees))
                return AccessDeniedView();

            //prepare model
            var model = await _employeeModelFactory.PrepareEmployeeSearchModelAsync(new EmployeeSearchModel());

            return View(EmployeeSearchModel.LIST_VIEW, model);
            //return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> List(EmployeeSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(APermissionProvider.ManageEmployees))
                return await AccessDeniedDataTablesJson();

            //prepare model
            var model = await _employeeModelFactory.PrepareEmployeeListModelAsync(searchModel);

            return Json(model);
        }

        #endregion

        #region Create / Edit / Delete

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(APermissionProvider.ManageEmployees))
                return AccessDeniedView();

            //prepare model
            var model = await _employeeModelFactory.PrepareEmployeeModelAsync(new EmployeeModel(), null);

            //return View(model);
            return View(EmployeeModel.CREATE_VIEW, model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual async Task<IActionResult> Create(EmployeeModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(APermissionProvider.ManageEmployees))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Controllers/Settings/EmployeeSettingController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Widgets.HumanResource.Areas.Admin.Factories;
using Nop.Plugin.Widgets.HumanResource.Areas.Admin.Models.Settings;
using Nop.Plugin.Widgets.HumanResource.Core.Domains.HumanResource;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;

namespace Nop.Plugin.Widgets.HumanResource.Areas.Admin.Controllers.Settings
{
    public partial class EmployeeSettingController : BaseAdminController
    {
        public const string ConfigureActionName = "Configure";
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IEmployeeSettingModelFactory _settingModelFactory;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public EmployeeSettingController(
            ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IEmployeeSettingModelFactory settingModelFactory,
            ISettingService settingService,
            IStoreContext storeContext
            )
        {
            _customerActivityService = customerActivityService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingModelFactory = settingModelFactory;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods
        [HttpGet, ActionName(ConfigureActionName)]
        public virtual async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //prepare model
            var model = await _settingModelFactory.PrepareEmployeeSettingsModelAsync();

            return View(EmployeeSettingsModel.View, model);
        }

        [HttpPost, ActionName(ConfigureActionName)]
        public virtual async Task<IActionResult> Configure(EmployeeSettingsModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                //load settings for a chosen store scope
                var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
                var employeeSettings = await _settingService.LoadSettingAsync<EmployeeSettings>(storeScope);
                employeeSettings = model.ToSettings(employeeSettings);

                //we do not clear cache after each setting update.
                //this behavior can increase performance because cached settings will not be cleared 
                //and loaded from database after each update
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.DefaultViewMode, model.DefaultViewMode_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.ShowShareButton, model.ShowShareButton_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.PageShareCode, model.PageShareCode_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.EmailAFriendEnabled, model.EmailAFriendEnabled_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.AllowAnonymousUsersToEmailAFriend, model.AllowAnonymousUsersToEmailAFriend_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.SearchPageAllowCustomersToSelectPageSize, model.SearchPageAllowCustomersToSelectPageSize_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.SearchPagePageSizeOptions, model.SearchPagePageSizeOptions_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.ExportImportEmployeesUsingEmployeeName, model.ExportImportEmployeesUsingEmployeeName_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.ExportImportAllowDownloadImages, model.ExportImportAllowDownloadImages_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.ExportImportRelatedEntitiesByName, model.ExportImportRelatedEntitiesByName_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.DisplayDatePreOrderAvailability, model.DisplayDatePreOrderAvailability_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.EmployeeBreadcrumbEnabled, model.EmployeeBreadcrumbEnabled_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.EnableSpecificationAttributeFiltering, model.EnableSpecificationAttributeFiltering_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.DisplayAllPicturesOnHumanResourcePages, model.DisplayAllPicturesOnHumanResourcePages_OverrideForStore, storeScope, false);
                await _settingService.SaveSettingOverridablePerStoreAsync(employeeSettings, x => x.AllowCustomersToSearchWithEmployeeName, model.AllowCustomersToSearchWithEmployeeName_OverrideForStore, storeScope, false);

                //now settings not overridable per store
                await _settingService.SaveSettingAsync(employeeSettings, x => x.IgnoreAcl, 0, false);

                //now clear settings cache
                await _settingService.ClearCacheAsync();

                //activity log
                await _customerActivityService.InsertActivityAsync("EditSettings", await _localizationService.GetResourceAsync(EmployeeSettingsModel.Labels.EditSettings));

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync(EmployeeSettingsModel.Labels.Updated));

                return RedirectToAction(ConfigureActionName);
            }

            //prepare model
            model = await _settingModelFactory.PrepareEmployeeSettingsModelAsync(model);

            //if we got this far, something failed, redisplay form
            return View(EmployeeSettingsModel.View, model);
        }

        #endregion
    }
}

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Views/Setting/Employee.cshtml
@model EmployeeSettingsModel

@{
    //page title
    ViewBag.PageTitle = T(EmployeeSettingsModel.Labels.Title).Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName(EmployeeSettingsModel.SYSTEM_NAME);
}

@{
    const string hideSearchBlockAttributeName = "HumanResourceSettingsPage.HideSearchBlock";
    var customer = await workContext.GetCurrentCustomerAsync();
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideSearchBlockAttributeName);

    const string hidePerformanceBlockAttributeName = "HumanResourceSettingsPage.HidePerformanceBlock";
    var hidePerformanceBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hidePerformanceBlockAttributeName);

    const string hideShareBlockAttributeName = "HumanResourceSettingsPage.HideShareBlock";
    var hideShareBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideShareBlockAttributeName);

    const string hideAdditionalSectionsBlockAttributeName = "HumanResourceSettingsPage.HideAdditionalSectionsBlock";
    var hideAdditionalSectionsBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideAdditionalSectionsBlockAttributeName);

    const string hideHumanResourcePagesBlockAttributeName = "HumanResourceSettingsPage.HideHumanResourcePagesBlock";
    var hideHumanResourcePagesBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideHumanResourcePagesBlockAttributeName);

    const string hideExportImportBlockAttributeName = "HumanResourceSettingsPage.HideExportImportBlock";
    var hideExportImportBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideExportImportBlockAttributeName);

}

@{
    // Helper to get string prefixed and sulfixed.
    string Gsf(string radical)
    {
        return "./" + radical + ".cshtml";
    }
}

<form asp-controller="EmployeeSetting" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T(EmployeeSettingsModel.Labels.Title)
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T(Common.Labels.Save)
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = PluginWidgetZones.HumanResourceSettingsButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @await Component.InvokeAsync(typeof(StoreScopeConfigurationViewComponent))
                @await Component.InvokeAsync(typeof(SettingModeViewComponent))
                <div asp-validation-summary="All"></div>

                <nop-cards id="hrsettings-cards">
                    <nop-card asp-name="hrsettings-search" asp-icon="fas fa-search" asp-title="@T(EmployeeSettingsModel.Labels.Search)" asp-hide-block-attribute-name="@hideSearchBlockAttributeName" asp-hide="@hideSearchBlock" asp-advanced="false">@await Html.PartialAsync(Gsf("_Employee.Search"), Model)</nop-card>
                    <nop-card asp-name="hrsettings-performance" asp-icon="fas fa-chart-line" asp-title="@T(EmployeeSettingsModel.Labels.Performance)" asp-hide-block-attribute-name="@hidePerformanceBlockAttributeName" asp-hide="@hidePerformanceBlock" asp-advanced="true">@await Html.PartialAsync(Gsf("_Employee.Performance"), Model)</nop-card>
                    <nop-card asp-name="hrsettings-share" asp-icon="fas fa-share-square" asp-title="@T(EmployeeSettingsModel.Labels.Share)" asp-hide-block-attribute-name="@hideShareBlockAttributeName" asp-hide="@hideShareBlock" asp-advanced="false">@await Html.PartialAsync(Gsf("_Employee.Share"), Model)</nop-card>
                    <nop-card asp-name="hrsettings-additional-sections" asp-icon="fas fa-plus" asp-title="@T(EmployeeSettingsModel.Labels.AdditionalSections)" asp-hide-block-attribute-name="@hideAdditionalSectionsBlockAttributeName" asp-hide="@hideAdditionalSectionsBlock" asp-advanced="false">@await Html.PartialAsync(Gsf("_Employee.AdditionalSections"), Model)</nop-card>
                    <nop-card asp-name="hrsettings-hr-pages" asp-icon="fas fa-th-list" asp-title="@T(EmployeeSettingsModel.Labels.HumanResourcePages)" asp-hide-block-attribute-name="@hideHumanResourcePagesBlockAttributeName" asp-hide="@hideHumanResourcePagesBlock" asp-advanced="true">@await Html.PartialAsync(Gsf("_Employee.HumanResourcePages"), Model)</nop-card>
                    <nop-card asp-name="hrsettings-export-import" asp-icon="fas fa-exchange-alt" asp-title="@T(EmployeeSettingsModel.Labels.ExportImport)" asp-hide-block-attribute-name="@hideExportImportBlockAttributeName" asp-hide="@hideExportImportBlock" asp-advanced="true">@await Html.PartialAsync(Gsf("_Employee.ExportImport"), Model)</nop-card>

                    @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = PluginWidgetZones.HumanResourceSettingsDetailsBlock, additionalData = Model })
                </nop-cards>
            </div>
        </div>
    </section>
</form>

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Views/Setting/_Employee.AdditionalSections.cshtml
@model EmployeeSettingsModel

<div class="card-body">

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="DisplayDatePreOrderAvailability_OverrideForStore" asp-input="DisplayDatePreOrderAvailability" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="DisplayDatePreOrderAvailability" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="DisplayDatePreOrderAvailability" />
            <span asp-validation-for="DisplayDatePreOrderAvailability"></span>
        </div>
    </div>
</div>

<script>

</script>

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Views/Setting/_Employee.ExportImport.cshtml
@model EmployeeSettingsModel

<div class="card-body">

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="ExportImportEmployeesUsingEmployeeName_OverrideForStore" asp-input="ExportImportEmployeesUsingEmployeeName" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="ExportImportEmployeesUsingEmployeeName" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="ExportImportEmployeesUsingEmployeeName" />
            <span asp-validation-for="ExportImportEmployeesUsingEmployeeName"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="ExportImportAllowDownloadImages_OverrideForStore" asp-input="ExportImportAllowDownloadImages" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="ExportImportAllowDownloadImages" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="ExportImportAllowDownloadImages" />
            <span asp-validation-for="ExportImportAllowDownloadImages"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="ExportImportRelatedEntitiesByName_OverrideForStore" asp-input="ExportImportRelatedEntitiesByName" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="ExportImportRelatedEntitiesByName" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="ExportImportRelatedEntitiesByName" />
            <span asp-validation-for="ExportImportRelatedEntitiesByName"></span>
        </div>
    </div>

</div>

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Views/Setting/_Employee.HumanResourcePages.cshtml
@model EmployeeSettingsModel

<div class="card-body">

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="DefaultViewMode_OverrideForStore" asp-input="DefaultViewMode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="DefaultViewMode" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="DefaultViewMode" asp-items="Model.AvailableViewModes" />
            <span asp-validation-for="DefaultViewMode"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="EmployeeBreadcrumbEnabled_OverrideForStore" asp-input="EmployeeBreadcrumbEnabled" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="EmployeeBreadcrumbEnabled" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="EmployeeBreadcrumbEnabled" />
            <span asp-validation-for="EmployeeBreadcrumbEnabled"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="EnableSpecificationAttributeFiltering_OverrideForStore" asp-input="EnableSpecificationAttributeFiltering" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="EnableSpecificationAttributeFiltering" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="EnableSpecificationAttributeFiltering" />
            <span asp-validation-for="EnableSpecificationAttributeFiltering"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-override-store-checkbox asp-for="DisplayAllPicturesOnHumanResourcePages_OverrideForStore" asp-input="DisplayAllPicturesOnHumanResourcePages" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
            <nop-label asp-for="DisplayAllPicturesOnHumanResourcePages" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="DisplayAllPicturesOnHumanResourcePages" />
            <span asp-validation-for="DisplayAllPicturesOnHumanResourcePages"></span>
        </div>
    </div>

</div>

Content/Nop.Plugin.Widgets.HumanResource/Areas/Admin/Views/Setting/_Employee.Performance.cshtml
@model EmployeeSettingsModel

<div class="card-body">
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="IgnoreAcl" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="IgnoreAcl" />
            <span asp-validation-for="IgnoreAcl"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="IgnoreStoreLimitations" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="IgnoreStoreLimitations" />
            <span asp-validation-for="IgnoreStoreLimitations"></span>
        </div>
    </div>

</div>